// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

void* winrt_make_BlankApp1_BrowserPage()
{
    return winrt::detach_abi(winrt::make<winrt::BlankApp1::factory_implementation::BrowserPage>());
}
namespace winrt::BlankApp1
{
    BrowserPage::BrowserPage() :
        BrowserPage(make<BlankApp1::implementation::BrowserPage>())
    {
    }
}
