// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

void* winrt_make_BlankApp1_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::BlankApp1::factory_implementation::MainPage>());
}
namespace winrt::BlankApp1
{
    MainPage::MainPage() :
        MainPage(make<BlankApp1::implementation::MainPage>())
    {
    }
}
