// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

void* winrt_make_BlankApp1_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::BlankApp1::factory_implementation::XamlMetaDataProvider>());
}
namespace winrt::BlankApp1
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<BlankApp1::implementation::XamlMetaDataProvider>())
    {
    }
}
