// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

#ifndef WINRT_BlankApp1_0_H
#define WINRT_BlankApp1_0_H
namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
namespace winrt::BlankApp1
{
    struct IBrowserPage;
    struct BrowserPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<BlankApp1::IBrowserPage>
    {
        using type = interface_category;
    };
    template <> struct category<BlankApp1::BrowserPage>
    {
        using type = class_category;
    };
    template <> struct category<BlankApp1::XamlMetaDataProvider>
    {
        using type = class_category;
    };
    template <> struct name<BlankApp1::IBrowserPage>
    {
        static constexpr auto & value{ L"BlankApp1.IBrowserPage" };
    };
    template <> struct name<BlankApp1::BrowserPage>
    {
        static constexpr auto & value{ L"BlankApp1.BrowserPage" };
    };
    template <> struct name<BlankApp1::XamlMetaDataProvider>
    {
        static constexpr auto & value{ L"BlankApp1.XamlMetaDataProvider" };
    };
    template <> struct guid_storage<BlankApp1::IBrowserPage>
    {
        static constexpr guid value{ 0xCEACB610,0x5872,0x540D,{ 0xAE,0xD6,0x8C,0x06,0xE8,0x48,0x3F,0x6E } };
    };
    template <> struct default_interface<BlankApp1::BrowserPage>
    {
        using type = BlankApp1::IBrowserPage;
    };
    template <> struct default_interface<BlankApp1::XamlMetaDataProvider>
    {
        using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider;
    };
    template <> struct abi<BlankApp1::IBrowserPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_BlankApp1_IBrowserPage
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<BlankApp1::IBrowserPage>
    {
        template <typename D> using type = consume_BlankApp1_IBrowserPage<D>;
    };
}
#endif
