// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

#ifndef WINRT_BlankApp1_0_H
#define WINRT_BlankApp1_0_H
namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
namespace winrt::BlankApp1
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<BlankApp1::IMainPage>
    {
        using type = interface_category;
    };
    template <> struct category<BlankApp1::MainPage>
    {
        using type = class_category;
    };
    template <> struct category<BlankApp1::XamlMetaDataProvider>
    {
        using type = class_category;
    };
    template <> struct name<BlankApp1::IMainPage>
    {
        static constexpr auto & value{ L"BlankApp1.IMainPage" };
    };
    template <> struct name<BlankApp1::MainPage>
    {
        static constexpr auto & value{ L"BlankApp1.MainPage" };
    };
    template <> struct name<BlankApp1::XamlMetaDataProvider>
    {
        static constexpr auto & value{ L"BlankApp1.XamlMetaDataProvider" };
    };
    template <> struct guid_storage<BlankApp1::IMainPage>
    {
        static constexpr guid value{ 0x3B6FC83D,0xB73D,0x56CF,{ 0x84,0xF2,0xF3,0x3D,0x93,0xFF,0x8B,0x28 } };
    };
    template <> struct default_interface<BlankApp1::MainPage>
    {
        using type = BlankApp1::IMainPage;
    };
    template <> struct default_interface<BlankApp1::XamlMetaDataProvider>
    {
        using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider;
    };
    template <> struct abi<BlankApp1::IMainPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_BlankApp1_IMainPage
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<BlankApp1::IMainPage>
    {
        template <typename D> using type = consume_BlankApp1_IMainPage<D>;
    };
}
#endif
