// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

#ifndef WINRT_BlankApp1_1_H
#define WINRT_BlankApp1_1_H
#include "winrt/impl/BlankApp1.0.h"
namespace winrt::BlankApp1
{
    struct __declspec(empty_bases) IBrowserPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBrowserPage>
    {
        IBrowserPage(std::nullptr_t = nullptr) noexcept {}
        IBrowserPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
